spring:
  application:
    name: hello-spring-cloud-consumer-feign

server:
  port: 8889

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: true

